version: "3.9"

services: 
  isaac:
    image: ghcr.io/isaacyav97/proyecto:3.0.0
    networks: 
      - traefik-public
    deploy: 
      replicas: 1
      update_config: 
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      # ¡AQUÍ ESTÁ LA MAGIA! Los labels ahora están dentro de "deploy"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.isaac.entrypoints=http"
        - "traefik.http.routers.isaac.rule=Host(`isaac.byronrm.com`)"
        - "traefik.http.middlewares.isaac-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.isaac.middlewares=isaac-https-redirect"
        - "traefik.http.routers.isaac-secure.entrypoints=https"
        - "traefik.http.routers.isaac-secure.rule=Host(`isaac.byronrm.com`)"
        - "traefik.http.routers.isaac-secure.tls=true"
        - "traefik.http.routers.isaac-secure.tls.certresolver=http"
        - "traefik.http.routers.isaac-secure.service=isaac"
        - "traefik.http.services.isaac.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true